services:
  db:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chat_network

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_redis_password --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - chat_network

  app:
    build: .
    container_name: chat_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - chat_network

volumes:
  pgdata:
  redis_data:

networks:
  chat_network:
    driver: bridge